---

- name: validate mandatory variables
  assert:
    that: item | mandatory
  loop:
    - shinobi_database_root_password
    - shinobi_database_user_name
    - shinobi_database_user_password
    - shinobi_super_user_email
    - shinobi_super_user_password

- name: install Python Docker modules
  become: yes
  pip:
    name:
      - "{{ item }}"
  loop:
    - docker
    - docker-compose

- name: create directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0770
  loop:
    - "{{ shinobi_data_directory }}"
    - "{{ shinobi_video_directory }}"
    - "{{ shinobi_role_source_directory }}"
    - "{{ shinobi_image_build_directory }}"

- name: copy Shinobi Docker files
  become: yes
  copy:
    src: files/docker-shinobi/
    dest: "{{ shinobi_image_build_directory }}"
    follow: yes

- name: setup containerised services
  become: yes
  docker_compose:
    build: yes
    project_name: shinobi
    project_src: "{{ shinobi_image_build_directory }}"
  environment:
    DATABASE_BASE_IMAGE: "{{ shinobi_docker_database_base_image }}"
    MYSQL_USER_NAME: "{{ shinobi_database_root_password }}"
    MYSQL_USER_PASSWORD: "{{ shinobi_database_user_name }}"
    MYSQL_ROOT_PASSWORD: "{{ shinobi_database_user_password }}"
    SHINOBI_DATA_LOCATION: "{{ shinobi_data_directory }}"
    SHINOBI_SUPER_USER_EMAIL: "{{ shinobi_super_user_email }}"
    SHINOBI_SUPER_USER_PASSWORD: "{{ shinobi_super_user_password }}"
    SHINOBI_VIDEO_LOCATION: "{{ shinobi_video_directory }}"
    SHINOBI_BASE_IMAGE: "{{ shinobi_docker_shinobi_base_image }}"
    SHINOBI_REPOSITORY_URL: "{{ shinobi_source.repository | default(None) }}"
    SHINOBI_REPOSITORY_BRANCH: "{{ shinobi_source.branch | default(None) }}"
    SHINOBI_HOST_PORT: "{{ shinobi_host_port }}"
