---

dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: shinobi-ansible-test
    image: colinnolan/molecule-docker-platforms:ubuntu-python3-dind
    privileged: True
    # TODO: remove this when push arm image to Dockerhub
    pull: False
    # TODO: remove
    exposed_ports:
      - 8080/tcp
    published_ports:
      - 0.0.0.0:8080:8080/tcp

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: playbook.yml
  config_options:
    defaults:
      interpreter_python: auto

verifier:
  name: testinfra
  lint:
    name: flake8
  env:
    TESTVARS_EXTRA_VARS: testvars.yml
