---

dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: shinobi-ansible-test
    image: colinnolan/molecule-docker-platforms:ubuntu-python3-dind
    privileged: True
    # TODO: remove this when push arm image to Dockerhub
    pull: False

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: playbook.yml

verifier:
  name: testinfra
  lint:
    name: flake8
