---

- name: Converge
  hosts: all

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    shinobi_database_root_password: password123
    shinobi_database_user_name: user123
    shinobi_database_user_password: password123
    shinobi_super_user_email: admin@localhost
    shinobi_super_user_password: password123
